# watch-labserver-logins.ps1 -- runs ON ROMULUS (scheduled hourly): polls
# labserver over SSH for (a) who is logged in right now and (b) new `hey`
# messages, appends both to logs\, and writes a desktop ALERT when Danny
# (deks) appears or sends something.
#
# Read-only on labserver: it reads /var/log/wtmp.db (world-readable sqlite),
# loginctl, and /srv/msg/chat.log. It changes nothing on Danny's box.
#
#   .\watch-labserver-logins.ps1              # one poll
#   .\watch-labserver-logins.ps1 -Install     # register the hourly task
#   .\watch-labserver-logins.ps1 -Uninstall   # remove it
#
# NO CONSOLE WINDOW EVER APPEARS. `-WindowStyle Hidden` alone does not achieve
# that: powershell.exe allocates a console first and hides it a moment later,
# and that is the flash. -Install picks whichever fix is available:
#   elevated     -> LogonType S4U, which runs in session 0 (no desktop at all)
#   not elevated -> launched via a wscript.exe .vbs shim, a GUI-subsystem host
#                   that starts powershell hidden from the outset
# Alerts land in a desktop file rather than a toast, because a session-0 task
# has no desktop to raise one on.
#
# KEEP THIS FILE PURE ASCII. The scheduled task runs powershell.exe (5.1),
# which reads .ps1 as ANSI -- a stray em-dash silently breaks string parsing
# even though pwsh 7 parses the same file fine. Saved UTF-8 with BOM.
[CmdletBinding()]
param(
    [switch]$Install,
    [switch]$Uninstall,
    [string]$TaskName = 'DG3030 - labserver login watch',
    [string]$Target   = 'jony@100.86.218.41',
    [string]$Me       = 'jony'
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path

# ---------------------------------------------------------------- install ---
if ($Install -or $Uninstall) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    if ($Uninstall) { "Removed scheduled task '$TaskName'."; return }

    $self = $MyInvocation.MyCommand.Path
    $elevated = ([Security.Principal.WindowsPrincipal] `
        [Security.Principal.WindowsIdentity]::GetCurrent()
        ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

    if ($elevated) {
        # Best case: S4U = no stored password, runs logged-on or not, and lands
        # in session 0 where no window can exist at all.
        $action = New-ScheduledTaskAction -Execute 'powershell.exe' `
            -Argument ('-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "{0}"' -f $self)
        $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
            -LogonType S4U -RunLevel Limited
        $mode = 'S4U / session 0 (runs whether you are logged on or not)'
    } else {
        # No elevation available. Interactive tasks flash a console because
        # powershell.exe allocates one before -WindowStyle Hidden takes effect.
        # wscript.exe is a GUI-subsystem host, so launching through a one-line
        # .vbs shim with window style 0 means no console is ever created.
        $shim = Join-Path $here 'watch-labserver-hidden.vbs'
        Set-Content -Encoding ASCII $shim @"
' Launches the watcher with no console window at all. Generated by
' watch-labserver-logins.ps1 -Install (non-elevated path). See that script.
CreateObject("WScript.Shell").Run _
  "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ""$self""", 0, False
"@
        $action = New-ScheduledTaskAction -Execute 'wscript.exe' `
            -Argument ('//nologo "{0}"' -f $shim)
        $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
            -LogonType Interactive -RunLevel Limited
        $mode = 'Interactive via wscript shim (runs only while you are logged on)'
    }

    $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddMinutes(5) `
        -RepetitionInterval (New-TimeSpan -Hours 1)
    $settings = New-ScheduledTaskSettingsSet -Hidden `
        -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
        -MultipleInstances IgnoreNew

    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Principal $principal -Settings $settings -ErrorAction Stop | Out-Null

    if (-not (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue)) {
        throw "Registration reported success but the task is not present."
    }
    "Registered '$TaskName' -- hourly, hidden."
    "  mode: $mode"
    if (-not $elevated) {
        "  (For the stronger session-0 variant, re-run -Install from an elevated prompt.)"
    }
    "  log : $here\logs\labserver-logins.csv"
    return
}

# ------------------------------------------------------------------ paths ---
$logDir = Join-Path $here 'logs'
if (-not (Test-Path $logDir)) { New-Item -ItemType Directory $logDir | Out-Null }
$csv       = Join-Path $logDir 'labserver-logins.csv'
$chatLog   = Join-Path $logDir 'labserver-chat.log'
$stateFile = Join-Path $logDir '.labserver-watch-state'
if (-not (Test-Path $csv)) { Set-Content $csv 'polled,status,sessions,newMessages' }

# Watermark: newest chat message epoch we have already recorded.
$since = 0
if (Test-Path $stateFile) { [int64]::TryParse((Get-Content $stateFile -Raw).Trim(), [ref]$since) | Out-Null }

# ----------------------------------------------------------- remote probe ---
# Base64 the python so nothing has to survive two layers of shell quoting --
# same lesson as the EncodedCommand trick in the FamilyNetwork README.
$py = @"
import subprocess, os
# loginctl, NOT wtmp.db, is the authority for who is live: wtmp.db records SSH
# logins only, so a console login on seat0/tty1 is invisible there. Class
# 'manager' rows are the per-user systemd instance, not a login.
try:
    out = subprocess.check_output(['loginctl','list-sessions','--no-legend']).decode()
    for line in out.splitlines():
        f = line.split()
        if len(f) >= 8 and f[5] == 'user':
            user, seat, tty, idle = f[2], f[3], f[6], f[7]
            where = ('console ' + tty) if seat != '-' else 'ssh'
            print('SESS|%s|%s|%s' % (user, where, idle))
except Exception as e:
    print('ERR|sessions|%s' % e)
p = '/srv/msg/chat.log'
if os.path.exists(p):
    try:
        with open(p, encoding='utf-8', errors='replace') as f:
            for line in f:
                parts = line.rstrip('\n').split('\t')
                if len(parts) >= 3 and '|' in parts[0]:
                    ep = int(parts[0].split('|')[1])
                    if ep > ${since}:
                        print('MSG|%d|%s|%s' % (ep, parts[1], parts[2]))
    except Exception as e:
        print('ERR|chat|%s' % e)
else:
    print('NOCHAT')
"@
# Feed the script on stdin rather than as an argument: a quoted python -c
# has to survive PowerShell's native-argument parser AND the remote shell,
# and it does not. stdin has no quoting layer at all. LF endings so python
# never sees a stray CR.
$py = $py -replace "`r`n", "`n"

$out = $null
try {
    $out = $py | ssh -o BatchMode=yes -o ConnectTimeout=15 $Target "python3 -" 2>$null
} catch { $out = $null }

$stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
if (-not $out) {
    Add-Content $csv "$stamp,UNREACHABLE,,"
    return
}

# ------------------------------------------------------------------ parse ---
$sessions = @(); $messages = @()
foreach ($line in $out) {
    $f = $line -split '\|'
    switch ($f[0]) {
        'SESS' { $sessions += [pscustomobject]@{ User=$f[1]; Where=$f[2]; Idle=$f[3] } }
        'MSG'  { $messages += [pscustomobject]@{ Epoch=[int64]$f[1]; User=$f[2]; Text=($f[3..($f.Count-1)] -join '|') } }
    }
}

$others    = @($sessions | Where-Object User -ne $Me)
$fromOther = @($messages | Where-Object User -ne $Me)

$who = if ($sessions) { ($sessions | ForEach-Object { $_.User }) -join '+' } else { 'none' }
Add-Content $csv "$stamp,ok,$who,$($messages.Count)"

# Append new chat traffic to a local transcript so Jon has the history offline.
foreach ($m in $messages) {
    $t = [DateTimeOffset]::FromUnixTimeSeconds($m.Epoch).LocalDateTime.ToString('yyyy-MM-dd HH:mm')
    Add-Content $chatLog ("{0}  {1,-6}  {2}" -f $t, $m.User, $m.Text)
}
if ($messages) { Set-Content $stateFile ([string]($messages | Measure-Object Epoch -Maximum).Maximum) }

# ------------------------------------------------------------------ alert ---
if ($others -or $fromOther) {
    $alert = Join-Path ([Environment]::GetFolderPath('Desktop')) 'ALERT-labserver.txt'
    $body = @("labserver activity -- $stamp", "")
    foreach ($s in $others) {
        $idle = if ($s.Idle -eq 'yes') { 'idle' } else { 'ACTIVE' }
        $body += "  LOGGED IN: $($s.User) via $($s.Where) - $idle"
    }
    if ($fromOther) {
        $body += ""
        $body += "  NEW MESSAGES:"
        foreach ($m in $fromOther) { $body += "    $($m.User): $($m.Text)" }
        $body += ""
        $body += "  Reply with:  ssh $Target hey `"your reply`""
    }
    $body += ""
    $body += "Full picture:  ssh $Target 'bash -s' < $here\diag-labserver-logins.sh"
    Set-Content $alert $body
}
