#!/usr/bin/env bash
# vps-apply-portmap.sh - turn portmap.conf into nftables DNAT rules on the VPS.
#
#   sudo bash vps-apply-portmap.sh --dry-run    # print the ruleset, change nothing
#   sudo bash vps-apply-portmap.sh              # validate, apply, persist
#
# Idempotent: the whole familynet_portmap table is replaced atomically each run,
# so re-running after editing portmap.conf is the normal way to change ports.
# It touches ONLY its own table - ufw/docker/other nftables rules are untouched.
set -euo pipefail

CONF="${CONF:-$(dirname "$0")/portmap.conf}"
WG_IF="${WG_IF:-wg0}"
WG_SUBNET="${WG_SUBNET:-10.8.0.0/24}"
TABLE="familynet_portmap"
PERSIST="/etc/nftables.d/familynet-portmap.nft"
DRY=0
[ "${1:-}" = "--dry-run" ] && DRY=1

declare -A HOSTS=( [romulus]=10.8.0.2 [remoria]=10.8.0.3 [bubba]=10.8.0.4 )

die(){ echo "ERROR: $*" >&2; exit 1; }
[ -r "$CONF" ] || die "cannot read $CONF"
[ "$DRY" = 1 ] || [ "$(id -u)" = 0 ] || die "must be root to apply (or use --dry-run)"
[ "$DRY" = 1 ] || command -v nft >/dev/null || die "nft not installed. apt install nftables"

WAN_IF="${WAN_IF:-$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1);exit}}')}"
[ -n "$WAN_IF" ] || die "could not auto-detect WAN interface; set WAN_IF=ethX"

# ---- parse + validate ------------------------------------------------------
span(){ case "$1" in *-*) echo $(( ${1##*-} - ${1%-*} ));; *) echo 0;; esac; }
portok(){ case "$1" in ''|*[!0-9-]*) return 1;; esac
          local lo=${1%-*} hi=${1##*-}
          [ "$lo" -ge 1 ] && [ "$hi" -le 65535 ] && [ "$lo" -le "$hi" ]; }

rules=""; n=0; skipped=0
while read -r name proto public target dport enabled _rest; do
  [ -z "${name:-}" ] && continue
  case "$name" in \#*) continue;; esac
  [ -z "${enabled:-}" ] && die "line '$name': expected 6 columns, got fewer"

  case "$enabled" in
    no|NO|No) skipped=$((skipped+1)); continue;;
    yes|YES|Yes) ;;
    *) die "line '$name': enabled must be yes|no, got '$enabled'";;
  esac
  case "$proto" in tcp|udp) ;; *) die "line '$name': proto must be tcp|udp, got '$proto'";; esac
  portok "$public" || die "line '$name': bad public port '$public'"
  portok "$dport"  || die "line '$name': bad target port '$dport'"
  [ "$(span "$public")" = "$(span "$dport")" ] || \
      die "line '$name': range widths differ ($public vs $dport) - nft cannot map those"

  ip="${HOSTS[$target]:-$target}"
  case "$ip" in
    *[!0-9.]*|"") die "line '$name': unknown target '$target' (not an alias, not an IPv4)";;
  esac

  rules+="        iifname \"$WAN_IF\" $proto dport $public dnat to ${ip}:${dport} comment \"$name\""$'\n'
  n=$((n+1))
done < "$CONF"

[ "$n" -gt 0 ] || die "no enabled rules in $CONF - nothing to do"

# ---- build ruleset ---------------------------------------------------------
# The create/delete/create idiom makes replacement atomic AND safe on first run.
ruleset="table ip $TABLE
delete table ip $TABLE
table ip $TABLE {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
$rules    }
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        oifname \"$WG_IF\" ip daddr $WG_SUBNET masquerade
    }
}"
# masquerade note: without it, replies from a Windows box would leave via its LAN
# default route instead of the tunnel and the connection would hang. Cost: the
# server sees $WG_IF's address as the client IP, not the player's real IP.

echo "# WAN interface : $WAN_IF"
echo "# tunnel        : $WG_IF ($WG_SUBNET)"
echo "# rules         : $n enabled, $skipped disabled"
echo
echo "$ruleset"

if [ "$DRY" = 1 ]; then echo; echo "(dry run - nothing applied)"; exit 0; fi

echo
echo "$ruleset" | nft -c -f - || die "nftables rejected the ruleset (nothing applied)"
echo "$ruleset" | nft -f -    || die "apply failed"
echo "applied."

# ---- forwarding + persistence ---------------------------------------------
if [ "$(sysctl -n net.ipv4.ip_forward)" != 1 ]; then
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
  echo "enabled net.ipv4.ip_forward"
fi
printf 'net.ipv4.ip_forward = 1\n' > /etc/sysctl.d/99-familynet-forward.conf

mkdir -p "$(dirname "$PERSIST")"
{ echo "#!/usr/sbin/nft -f"; echo "# generated by vps-apply-portmap.sh - edit portmap.conf, not this"; echo "$ruleset"; } > "$PERSIST"
chmod 0750 "$PERSIST"
if [ -f /etc/nftables.conf ] && ! grep -q 'nftables.d' /etc/nftables.conf; then
  echo 'include "/etc/nftables.d/*.nft"' >> /etc/nftables.conf
  echo "added include line to /etc/nftables.conf"
fi
systemctl enable --now nftables >/dev/null 2>&1 || true
echo "persisted to $PERSIST (survives reboot)"

if command -v ufw >/dev/null && ufw status 2>/dev/null | grep -q '^Status: active'; then
  fp=$(grep -s '^DEFAULT_FORWARD_POLICY' /etc/default/ufw | cut -d'"' -f2)
  [ "$fp" = "ACCEPT" ] || cat <<'WARN'

WARNING: ufw is active with DEFAULT_FORWARD_POLICY != ACCEPT.
Your DNAT rules are correct but ufw will DROP the forwarded packets.
Fix:  sudo sed -i 's/^DEFAULT_FORWARD_POLICY.*/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw && sudo ufw reload
WARN
fi

echo
echo "Verify from OUTSIDE the house (phone on cellular, wifi OFF):"
echo "  nc -vz <vps-public-ip> 25569"
